#!/bin/sh -e
USER=peerbanhelper
getent passwd peerbanhelper > /dev/null || adduser --system --group --no-create-home --disabled-password --home /etc/peerbanhelper $USER
chown -R $USER: /etc/peerbanhelper
systemctl enable --now peerbanhelper.service 2> /dev/null
