#!/bin/sh -e
USER=peerbanhelper
getent passwd peerbanhelper > /dev/null || adduser --quiet --system --group --home /opt/peerbanhelper $USER
chown -R $USER: /etc/peerbanhelper
systemctl enable --now peerbanhelper.service 2> /dev/null
